# 个人信息
site_name: 小风的代码世界
site_url: https://www.cloudinwind.github.io
site_author: 小风

repo_name: cloudinwind/cloudinwind.github.io
repo_url: https://github.com/cloudinwind/cloudinwind.github.io

edit_uri: blob/main/docs/

theme:
  name: material
  language: zh
  custom_dir: overrides
  logo: https://pic.imgdb.cn/item/66d2d740d9c307b7e91a82b4.jpg
  favicon: https://pic.imgdb.cn/item/66d2d740d9c307b7e91a82b4.jpg

  font:
    text: Roboto Slab
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  # 设置日间模式和夜间模式的切换
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: default # 上方的
      accent: indigo # 链接等可交互元件的高亮色
      # teal 
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black 
      accent: indigo
      # teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  
  
  features:
    - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    # - navigation.instant 
    #- header.autohide  #自动隐藏
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
    - navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - content.tabs.link
    - content.tooltips
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.code.annotate 

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cloudinwind
    - icon: fontawesome/regular/envelope
      link: mailto:<cloudinwind@out.com> #联系方式
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com
    - icon: fontawesome/brands/x-twitter 
      link: https://twitter.com


plugins:
  - search:
      lang: zh
  - tags:
      tags_file: tags.md  #指定应使用哪个文件来呈现标签索引

# LaTeX支持
# markdown_extensions:
#   - pymdownx.arithmatex:
#       generic: true
#   - admonition
#   - pymdownx.details
#   - pymdownx.tilde
#   - pymdownx.superfences
#   - pymdownx.critic
#   - pymdownx.caret
#   - pymdownx.keys
#   - pymdownx.mark
#   - pymdownx.highlight:
#       use_pygments: true
#   - footnotes
#   - def_list
#   - pymdownx.tasklist:
#       custom_checkbox: true
#   - pymdownx.tabbed:
#       alternate_style: true
#   - attr_list
#   - md_in_html

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true

extra_css:
  - stylesheets/custom.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/waifu/autoload.js  # 十分耗时，放在最后加载